### ISSUE TITLE
Asynchronous loading of diff files

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/git-igitt#23]
Currently, scrolling through the graph may lag for commits with lots of changed files.

Loading of diffs could be done asynchronous for lag-free scrolling, while it may take a moment to show the file list.

**Comment by mlange-42** [comment]
@adamreichold Seems like I definitely need your help for this. First attempts failed with:

```
    = help: within `git2::Commit<'_>`, the trait `Sync` is not implemented for `*mut libgit2_sys::git_commit`
    = note: required because it appears within the type `git2::Commit<'_>`
    = note: required because of the requirements on the impl of `Send` for `&git2::Commit<'_>`
    = note: required because it appears within the type `[closure@src\app.rs:697:24: 699:6]`
```

**Comment by adamreichold** [comment]
I guess this just says that the underlying libgit2 library is not thread safe, c.f. https://github.com/libgit2/libgit2/blob/main/docs/threading.md, and hence `Commit` is neither `Send` nor `Sync`. Since it also does not support asynchronous operation on a single thread (e.g. via callback or `std::future::Future`), this seems to rule out asynchronous usage of a single `Repository` object and its dependent child objects via multiple threads/tasks.

I see three options to push this forward nonetheless:
*  Never share a `Repository` between threads by opening the same repository again on the background threads. Only identifiers like commit hashes or object ID are sent to other threads which need to resolve e.g. the corresponding commit again. This should be safe as Git needs to be prepared for some other process concurrently accessing the underlying repository files anyway. It would probably be relatively inefficient, yet should be reasonably simple to implement.
* Implement your own poor man's concurrency by manually yielding control back to the UI. For example, when the currently selected commit is changed, only update the summary and check again for keyboard evens before printing the diff (possibly even delayed by a timer). This is efficient and relatively simple, but it does not remove the lag, it just allows fast scrolling even with the lag present. 
* Completely separate UI and repository access into two separate threads. These then communicate via message passing, e.g. using the standard libraries channels, passing commands like "open this commit and its diff" and passing back results like the commit summary and later the fully formed diff that just needs to be printed. This should be efficient and general, but it is probably also the most intrusive change.

One caveat to this discussion that you should have ensured by measurement that the repository operations are indeed what causes the lag and not e.g. printing the text.

Another point that one could consider off-topic but I find relevant is that considering the amount of effort required to resolve this, it might either be better to just live with it or if you are willing to invest the effort, invest it into making this an improvement to `git log --graph`, `gitk` or `tig` instead.

**Comment by mlange-42** [comment]
Thanks for the explanations!

Resolved by delaying loading of diffs. Diff files are only loaded when the user stops scrolling throughthe graph.
