### ISSUE TITLE
Release for Linux (on WSL) much slower than Windows version

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/git-igitt#4]
While selection runs through the graph without any lag when holding an arrow key on Windows, there is heavy lag on Linux/WSL.

Version: 0.1.1

**Comment by mlange-42** [comment]
@adamreichold @hnolzen Can you confirm that on a "real" Linux machine?

**Comment by mlange-42** [comment]
Turns out that this is only a problem when accessing a Git repository in the Windows file system, i.e. under `/mnt/c/...`.

**Comment by adamreichold** [comment]
This is also specific to WSL2, c.f. https://docs.microsoft.com/en-us/windows/wsl/compare-versions

**Comment by mlange-42** [comment]
@adamreichold Thanks! Your link reads like WSL2 is faster (while I interprete your comment to the contrary?), and I already upgraded to WSL2 before.

A trial with binaries and the git repo on the "Linux side" of the file system showed that is runs nicely fast there, so I closed this issue.

**Comment by adamreichold** [comment]
> Your link reads like WSL2 is faster (while I interprete your comment to the contrary?), and I already upgraded to WSL2 before.

The salient point is "Performance across OS file systems" which WSL1 has and WSL2 does not. WSL1 is an emulation layer on top of the NT kernel and hence it has direct access to the Windows filesystem but needs to emulate the Linux filesystem which is why it has good performance in both cases. WSL2 is virtualisation and hence it has near-to-native access speed for the native Linux filesystem but accessing the Windows filesystem is comparable to a networked filesystem.
